<?php include 'incl_component_webpage_head.php'; ?>
<?php include 'incl_component_webpage_navbar.php'; ?>
<?php include 'incl_component_webpage_banner1.php'; ?>
<?php include 'incl_component_webpage_modal_support.php'; ?>
<?php include 'incl_component_webpage_container_ourmission.php'; ?>
<?php include 'incl_component_webpage_banner2.php'; ?>
<?php include 'incl_component_webpage_container_about.php'; ?>
<?php include 'incl_component_webpage_banner1.php'; ?>
<?php include 'incl_component_webpage_container_about_background_historical.php'; ?>
<?php include 'incl_component_webpage_banner2.php'; ?>
<?php include 'incl_component_webpage_container_about_background_scientific.php'; ?>
<?php include 'incl_component_webpage_banner1.php'; ?>
<?php include 'incl_component_webpage_container_about_goals_fundraising.php'; ?>
<?php include 'incl_component_webpage_banner2.php'; ?>
<?php include 'incl_component_webpage_container_contact.php'; ?>
<?php include 'incl_component_webpage_banner1.php'; ?>
<?php include 'incl_component_webpage_footer.php'; ?>
<?php include 'incl_component_webpage_scripts.php'; ?>
<?php include 'incl_component_webpage_end.php'; ?>
